[build]
builder = "NIXPACKS"

[deploy]
"startCommand": "gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT scraper:app"
[[deploy.cron]]
schedule = "*/5 * * * *"
command = "python run_scanner.py"
